### ISSUE TITLE
MAMP PRO

### ISSUE THREAD

**Issue by farlandlee** [ifunk/smtp-catcher#3]
is it possible to use this script with MAMP PRO?  I would assume so, but I am not having any success setting it up.  I have followed the directions making the changes to the php.ini file inside MAMP PRO and I changed the first line of the script to `#!/Applications/MAMP/bin/php` which is where the php.ini file is located.  Did I miss something?  Thanks for any help.

**Comment by adamroyle** [comment]
I have not used MAMP PRO so I've never tried to get this working. I don't see any reason why it shouldn't work, it's probably just a matter of correct paths for php.ini, sendmail_path and php cli and ensuring you reload the server after php.ini modifications.
